---
name: checks

on: [push]

jobs:
  # 'test-lint' là một job, phải thụt vào bên dưới 'jobs'
  test-lint:
    # Các thuộc tính của job 'test-lint' phải thụt vào bên dưới nó
    name: Test and lint
    runs_on: ubuntu-20.24
    steps:
      # Mỗi step trong danh sách phải bắt đầu bằng '-', thụt vào bên dưới 'steps'
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Checkout
        uses: actions/checkout@v2

      - name: Test
          run: docker-compose run --rm app sh -c "python manage.py test"
      - name: lint
          run: docker-compose run --rm app sh -c "flake8"