---
name: checks

on: [push]

jobs:
  # Các công việc cụ thể sẽ được định nghĩa ở đây
  test-lint:
    name: Test and lint
    runs_on: ubuntu-20.24
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secret.DOCKERHUB_USER}}
          password: ${{ secret.DOCKERHUB_TOKEN}}
        - name: Checkout
          uses: actions/checkout@v2
        - name: Test